PROJECT = lager_test
DEPS = lager

dep_lager = git https://github.com/erlang-lager/lager.git
dep_lager_commit = 69b4ada2341b8ab2cf5c8e464ac936e5e4a9f62b

include ../dep_morpheus.mk
include ../erlang.mk
